#!/bin/bash

INPUT_FILE=$1
ORIGINAL_BIN_FILE="original-bin"
ORIGINAL_TXT_FILE="original-txt"

MODIFIED_BIN_FILE="modified-bin"
MODIFIED_TXT_FILE="modified-txt"

cp $INPUT_FILE $ORIGINAL_BIN_FILE
xxd -p $ORIGINAL_BIN_FILE > $ORIGINAL_TXT_FILE
cp $ORIGINAL_TXT_FILE $MODIFIED_TXT_FILE
vim $MODIFIED_TXT_FILE
xxd -r -p $MODIFIED_TXT_FILE > $MODIFIED_BIN_FILE
dd if=$MODIFIED_BIN_FILE of=$INPUT_FILE

